### ISSUE TITLE
大佬，能支持vless嘛

### ISSUE THREAD

**Issue by moliwei** [zzzgydi/clash-verge#406]
大佬，能支持vless嘛~

**Comment by zzzgydi** [comment]
切换clash-meta核心就ok了

**Comment by cw4t** [comment]
怎么切换呢，重启不生效啊

**Comment by zzzgydi** [comment]
> 怎么切换呢，重启不生效啊

设置页 - Clash 核心旁边的icon点一下，在弹窗里选clash meta。重启不生效是指的什么。

**Comment by cw4t** [comment]
这样操作后，还是报错不支持vless ---- 回复的原邮件 ***@***.***>发送日期2023年04月23日 13:26 ***@***.***> ***@***.***>***@***.***>主题Re: [zzzgydi/clash-verge] 大佬，能支持vless嘛 (Issue #406)

怎么切换呢，重启不生效啊

设置页 - Clash 核心旁边的icon点一下，在弹窗里选clash meta。重启不生效是指的什么。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/zzzgydi/clash-verge/issues/406#issuecomment-1518947217",
"url": "https://github.com/zzzgydi/clash-verge/issues/406#issuecomment-1518947217",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zzzgydi** [comment]
报错信息提供一下
