### ISSUE TITLE
token=的机场订阅导入了都不显示节点

### ISSUE THREAD

**Issue by screaminrain** [zzzgydi/clash-verge#41]
如题  clash=1这种就行 还有订阅转换了的都可以

**Comment by zzzgydi** [comment]
目前没有内置啥转换的功能。如果希望添加的话，可以把链接的响应体相关信息提供一下。响应头一些信息和确认响应体是不是utf8编码的符合clash yaml格式啥的。

**Comment by betaxab** [comment]
@zzzgydi These are using the v2board panel, there is only use one subscription URL, easy for users to remember and save (Don't think about which subscription link should we use).

And it determines the client type by User-Agent (because HTTP_USER_AGENT param has nothing, by default the v2board API will return v2rayN's subscription format).

As I said in my last issue, https://github.com/zzzgydi/clash-verge/issues/13 I really wish clash-verge would have a default UA (e.g. clash-verge/v0.x.x). The first advantage is more convenience, the second advantage is easy to version control. For example, when a breaking change is made in the clash core configuration, simply determine the version number in the UA, and make a compatibility or alert accordingly.

😸

**Comment by zzzgydi** [comment]
@betaxab I get it. I will add a default UA in the next version!

**Comment by zzzgydi** [comment]
@betaxab v0.0.29 supports default UA now.
