### ISSUE TITLE
Proxy2: Unsupported xtls flow type: xtls-rprx-vision

### ISSUE THREAD

**Issue by luozhouyang** [zzzgydi/clash-verge#509]
<img width="912" alt="截屏2023-04-09 21 06 39" src="https://user-images.githubusercontent.com/34032031/230774359-68b06e50-b9a5-4d76-a8b2-03401052e19e.png">

**Comment by Mr-Spade** [comment]
What kernel are you using? If it is the meta kernel, it should be because the clash-meta kernel has not been upgraded to the latest. You can manually download and replace the clash-meta kernel. I'm guessing that the next version of clash-verge will ship with an updated meta kernel that fixes this issue.
